version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: PORTALDOCOMPRADOR
      MYSQL_USER: gmartins
      MYSQL_PASSWORD: administrador
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    ports:
      - "8484:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my-network

volumes:
  mysql-data:

networks:
  my-network:
