/* Inicio Tabela de Usuários */
CREATE TABLE USUARIOS(
	UserID INT NOT NULL AUTO_INCREMENT, 
		FirstName VARCHAR (100) NOT NULL,
		LastName VARCHAR (100) NOT NULL, 
		Email VARCHAR (100) NOT NULL UNIQUE,
		UserName VARCHAR (50) NOT NULL UNIQUE, 
		CreateDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
		UpdateDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
		UserPerfil VARCHAR(50) NOT NULL DEFAULT "DEFAULT",
		DataNascimento DATE NOT NULL,
		PRIMARY KEY (UserID));
/* Fim Tabela de Usuários */